#include "toyc/codegen.h"

#include <ostream>

namespace toyc {

void CodeGenerator::emitProgram(const ast::TranslationUnit& unit,
                                std::ostream& out) const {
  bool hasGlobals = false;
  for (const auto& item : unit.items) {
    if (dynamic_cast<const ast::GlobalDecl*>(item.get()) != nullptr) {
      hasGlobals = true;
      break;
    }
  }

  out << "# Placeholder RISC-V32 generated by the ToyC skeleton\n";
  out << "# Replace src/codegen.cpp with a real backend implementation\n\n";

  if (hasGlobals) {
    out << ".data\n";
    for (const auto& item : unit.items) {
      const auto* global = dynamic_cast<const ast::GlobalDecl*>(item.get());
      if (global == nullptr) {
        continue;
      }
      out << ".globl " << global->decl->name << '\n';
      out << global->decl->name << ":\n";
      out << "  .word 0\n\n";
    }
  }

  out << ".text\n";
  for (const auto& item : unit.items) {
    const auto* func = dynamic_cast<const ast::FuncDef*>(item.get());
    if (func == nullptr) {
      continue;
    }

    out << ".globl " << func->name << '\n';
    out << func->name << ":\n";
    out << "  # TODO: emit prologue, body, and epilogue\n";
    if (!func->returnsVoid) {
      out << "  li a0, 0\n";
    }
    out << "  ret\n\n";
  }
}

}  // namespace toyc
